### ISSUE TITLE
Need to not Sanatize div  id names in WYSISYG editor

### ISSUE THREAD

**Issue by JMomentage** [pencilblue/pencilblue#976] opened 2016-03-23 18:53 UTC
I need to create pages that have links to named anchors in the WYSIWYG editor (so the user can later edit them). I could make this a custom page theme, but that will not allow the user to edit page. 
What is the best way to create a sanitization filter to omit the name divs for anchor links? 

Thanks!

**Comment by blakecallens** [comment] 2016-03-24 18:29
Duplicate of #977

**Closed** 2016-03-24 18:29 UTC
Labels: duplicate
