### ISSUE TITLE
Page Url Characters 404

### ISSUE THREAD

**Issue by alexcurtis** [pencilblue/pencilblue#475] opened 2015-02-19 13:47 UTC
When creating a page url with a non-alphanumeric character such as '-' like: about-us.
returns a 404 when navigating to that page.
No error in the console log.

**Comment by blakecallens** [comment] 2015-02-19 14:35
Confirmed this is only with the default pencilblue theme. Portfolio works fine.

**Comment by blakecallens** [comment] 2015-02-19 14:51
Looks like the issue is that the custom URL qualifies as a valid ObjectID, so the controller is trying to load it as such and coming up with no results. Figuring out a fix.

**Comment by alexcurtis** [comment] 2015-02-19 14:53
@blakecallens Thanks for the quick response.

**Comment by alexcurtis** [comment] 2015-02-19 15:04
Not sure if this is related but in the portfolio theme.
If I create a page called 'our-history' and setup the navigation to point to that page.
The url snaps to the object id rather than the nice url => /page/54e5e7fbf9e59cb243020971

**Comment by blakecallens** [comment] 2015-02-19 15:07
@alexcurtis page and article navigation objects are set to point to the permalink of the article or page. That way, if you change the custom URL, the navigation won't break. If you want to use the custom URL, create a *link* navigation item.

This error is fixed in branch PB475. I'll be putting a pull request in for @brianhyder to review before it makes its way to master.

**Closed by blakecallens** 2015-02-19 15:07 UTC
Labels: blocker, bug
