### ISSUE TITLE
New navigation item: Page -> Content: This field is required

### ISSUE THREAD

**Issue by marcellkiss** [pencilblue/pencilblue#541] opened 2015-04-09 14:36 UTC
When I'm trying to add a page navigation item on:
http://localhost:8080/admin/content/navigation/new
I get:
'This field is required' for the content field
I don't see JavaScript errors nor failed Ajax requests, and I tried many different inputs.
Do I something wrong?

**Comment by blakecallens** [comment] 2015-04-09 15:53
Are adding a page in that field? It does a real time search for the title of a page and gives you a combobox option.

**Comment by marcellkiss** [comment] 2015-04-09 16:14
I have just one page on /page/index, Headline is "Hello" and whatever I'm typing I don't get any options, the search icon doesn't work either.
I tried it in Chrome and Firefox and the result is the same.

**Comment by blakecallens** [comment] 2015-04-13 12:39
Tested on my local installation and was able to find all articles and pages by headline and confirmed that the search is case insensitive and live updating with typing.

This is being covered by #467 (which will change this element altogether) and this report will be obsolete when that one's complete, so I'm going to close this one.

@marcellkiss if you can provide console output, we might be able to find the reason you're having an issue. Otherwise, this will be a new interface element in the not too distant future.

**Closed by blakecallens** 2015-04-13 12:39 UTC
Labels: can't reproduce
