### ISSUE TITLE
Cannot connect to other database

### ISSUE THREAD

**Issue by Jean-PhilippeD** [pencilblue/pencilblue#744] opened 2015-09-15 12:21 UTC
Hi,

I'm not sure if I'm doing correctly the job, I want to count documents in a database which is not pencilblue's db.

I've tried :

>        var dao  = new pb.DAO(<dbName>);
>        dao.count(<collections>,{}, function(err, count) {
>                self.ts.registerLocal('count',count);
>                self.ts.load('/modules/test, function(err, result) {
>                      cb({content: result});
>                });

And I still get 0 count.
If I let dbName null or "pencilblue" and I choose a collection which exist, I get the right count.

What am I doing wrong ? Should I use DBManager to iniate connection ?? 

I'm sorry if it's not the proper place for this kind of question....

Thanks !

**Comment by brianhyder** [comment] 2015-09-15 13:28
Happy to help out.  What branch and/or version are you working off of?

**Comment by brianhyder** [comment] 2015-09-15 13:51
@Jean-PhilippeD could you also share the ```db``` section from your config.js file?

**Comment by brianhyder** [comment] 2015-09-15 13:53
I think the issue is in the DbManager.  It doesn't take into account the name of the db that is passed into the function.  It only takes into account the name that is part of the configuration.

**Comment by brianhyder** [comment] 2015-09-15 13:54
Solution will probably along the lines of modifying the piece of code that builds the mongo connection string: https://github.com/pencilblue/pencilblue/blob/master/include/dao/db_manager.js#L74

to accept an override DB name.

**Comment by Jean-PhilippeD** [comment] 2015-09-15 14:05
I'm using pencilblue 0.4.1.
My piece of config.js :
>    "db": {
>        "type": "mongo",
>        "servers": [
>            "mongodb://127.0.0.1:27017/"
>        ],
>       "name": "pencilblue",
>        "writeConcern": 1
>    },

When I print with console.log(dao)
I can see {dbname: <my db>} but it doesn't work (I've also tried the method entityExists witout success.)

I will check the db_manager !

**Comment by Jean-PhilippeD** [comment] 2015-09-15 15:02
Line 74:
>var dbURL = DBManager.buildConnectionStr(pb.config);
I think whatever the DB Name you give, it builds with name in config.js

I've just added line 73 :
>            if(name && name != pb.config.db.name){
>                pb.config.db.name = name;
>            }

And it seems to work. This is probably not the cleaner way... :)

**Comment by brianhyder** [comment] 2015-09-15 15:28
@Jean-PhilippeD Thank you for confirming.  I'll see if I can't clean that up and get it merged in tonight.

**Comment by brianhyder** [comment] 2015-09-17 13:07
@Jean-PhilippeD I merged a fix into the 0.5.0 branch.

**Closed by brianhyder** 2015-09-17 13:07 UTC
Labels: bug
