### ISSUE TITLE
publish_date: null is allways send to the server

### ISSUE THREAD

**Issue by bitterulf** [pencilblue/pencilblue#489] opened 2015-03-09 14:08 UTC
No matter what date i enter into the date picker the client allways sends null to the server.
This could be a date format problem with other languages but i don't know how to change the language in the backend to validate that.

**Comment by brianhyder** [comment] 2015-03-09 14:11
Can you send us which browser you are using?

**Comment by bitterulf** [comment] 2015-03-09 14:12
Firefox 36.0.1

**Comment by brianhyder** [comment] 2015-03-09 14:23
Hmm... I know we made improvements to try and fix that particular issue. A
couple of follow up questions. Version or commit of PB you are using and
active theme.

**Comment by brianhyder** [comment] 2015-03-09 14:24
Sorry, two more. Your time zone and does this happen in a different
browser?

**Comment by bitterulf** [comment] 2015-03-09 14:59
tracked down the problem to the parsableDate filter:
a wrong offsetstring ("+0-1:00") makes the date invalid.

now.getTimezoneOffset()  is -60 for me

**Comment by blakecallens** [comment] 2015-03-09 15:04
I'm unable to reproduce on 35.0.1 on Mac. Downloading the latest version now.

**Comment by blakecallens** [comment] 2015-03-09 15:17
Ok, I'm getting T - 60 minutes too in 36.0.1

**Comment by blakecallens** [comment] 2015-03-09 15:26
Looking into it, @bitterulf. I'm getting one hour less than expected for GMT -5:00 because we went into daylight savings this weekend and Europe didn't. Still unable to reproduce your null value error.

On line 22 of parsable_date.js can you add:
```JavaScript
console.log(dateArray);
```
and let me know what the output is? Thanks.

**Comment by bitterulf** [comment] 2015-03-10 08:17
Array [ "03", "10", "2015", "09", "16" ] 
and the offsetString is "+0-1:00"

**Comment by blakecallens** [comment] 2015-03-11 17:38
Ok, this looks like it was an error in the way we build the string east of GMT. I've made a change and merged it into master.

**Closed by blakecallens** 2015-03-11 17:38 UTC
