### ISSUE TITLE
Latest master does not persist active theme.

### ISSUE THREAD

**Issue by evanadams28** [pencilblue/pencilblue#629] opened 2015-06-02 16:56 UTC
Custom theme templates are not being routed to as of the latest revision of the master branch. The active theme becomes undefined or defaulted to the pencilblue theme even though a custom theme is set to active.

**Comment by brianhyder** [comment] 2015-06-02 17:19
Thanks for the report. We'll take a look.  We recently made a couple of changes to boost performance and reduce the number of times the active_theme setting was retrieved per request.  We probably missed something.

To recap, if I installed say the portfolio plugin and set it to active theme it would not route appropriately when the home page is called?

If you change the logging level to ```silly``` there will be a line that looks like ```Setting on theme xyz```.  What does that output for you?

**Comment by evanadams28** [comment] 2015-06-02 17:49
Yes, that scenario would be what I'm seeing. I changed the logging level to silly, but I didn't see the line you were talking about. Instead, I threw a console.log(this.activeTheme); in the template service (which of course gets hit a gazillion times) and the start of the log trail is the following on the home page load of the portfolio theme:

portfolio
undefined
undefined
pencilblue
pencilblue
pencilblue
...

Then, it stays pencilblue for the remainder of the page load. This is of course with the portfolio theme set to active.

Hope this helps? I'll try to get the silly log level working in the meantime to get you better info.

Thanks for your hasty response!

**Comment by evanadams28** [comment] 2015-06-02 18:17
I got the silly logging to work. So, I added a dummy custom theme, a dummy custom page, and also a dummy custom page to the portfolio theme. This is what I'm seeing when I go to the route with the portfolio theme active:

`2015-06-02T18:09:53.076Z - silly: [M] RequestHandler: Found static route [/customPageForTesting]
2015-06-02T18:09:53.076Z - silly: [M] SettingService1: Checking Service [DB] for Key [active_theme]
2015-06-02T18:09:53.077Z - silly: [M] RequestHandler: Settling on theme [custom_theme_for_testing] and method [GET] for URL=[GET:/customPageForTesting]`

Shouldn't it be settling on the portfolio theme and not my dummy custom theme, given that I have the portfolio theme active?

**Comment by brianhyder** [comment] 2015-06-02 18:32
Thank you for the info. It would settle on the portfolio theme if the route
was supported by portfolio. Since it is not then it settles on the theme
that supports it.

**Comment by brianhyder** [comment] 2015-06-02 22:31
@evanadams28 I wasn't able to reproduce it with the portfolio and dev-blog theme using ```/blog``` endpoint so I'm trying to narrow down a couple of items. 

Your console.log statement that outputted the active theme in the template service, where was it placed?  Not all instances of the TemplateService are passed the active theme in the constructor.  Sometimes it must be discovered by retrieving the setting (see ```TemplateService.prototype._getActiveTheme```).  My guess is that you are seeing undefined because it was not passed to the constructor.  That is OK.  

The part I'm concerned about is that it settled on theme on an inactive theme that had the route.  

* When the instance starts up do you see the /customPageForTesting route get registered (should be in the console output with silly turned on).  Any controllers that couldn't be required will have error statements in the logs.
* Would you mind sharing your config.js file so I can make sure the configurations line up?
* With multiple themes installed does the home page route correctly?
* What was the original page that you hit that caused the issue?

**Comment by brianhyder** [comment] 2015-06-08 01:17
@evanadams28 Are you still having issues with this?

**Comment by djwhatley** [comment] 2015-06-12 01:08
I have been having an issue with templates in the active theme not overriding base templates. Was able to circumvent it by overriding the appropriate controller, but I just removed the controller to see if it is working properly now, and it still does not appear to be overriding the default templates.

**Comment by JahlomP** [comment] 2015-06-12 15:27
The frontend of my theme is working but the custom admin section I wrote isn't. my custom fields on add new articles page are no more there. It defaults to pencilblue plugin.

**Comment by blakecallens** [comment] 2015-06-12 15:32
Make sure that the template file is still the same in the controller. We consolidated the add and edit articles pages into a single article_form template with the Angular forms update a few months back.

**Comment by evanadams28** [comment] 2015-06-12 15:37
@brianhyder Yes, I am still seeing the issue. I pulled from master again this morning and I'm seeing what @djwhatley described. Active theme's plugin templates are not properly overriding base templates. I'm actually passing my investigation on to @cchatham. She will get back to you with more details about the issue in this thread. She will actually find the root cause in code and get back to you on it. Please leave this issue open until you see a response from @cchatham.

**Comment by brianhyder** [comment] 2015-06-12 16:35
Awesome,

thank you guys for working through this one with us.

**Comment by JahlomP** [comment] 2015-06-12 17:35
@blakecallens, I will look at it and report

**Comment by cchatham** [comment] 2015-06-12 18:02
Okay so here is the lowdown:

Setup and Backstory:
* Pulled directly from Pencilblue master branch - Portfolio looks fine.
* Pulled down and installed one of our private plugins:
..* This plugin interfaces with internal APIs, adds routes to our app, and has default templates (just in case our theme does not override.)
..* I will call this Job.
* Pulled down our private theme plugin and installed:
..* This plugin defines the html and css for the careerbuildercareers.com theme.
..* This plugin also overrides the Index controller

What Happened:
* Landing Page respects the active theme just fine:
..* I set the active theme to portfolio -> go to root url '/' -> Portfolio's logo and nav bar. Great! :)
..* I set the active theme to our custom theme (the careerbuildercareers.com one) -> got to '/' -> careerbuildercareers.com landing page shows up! Great! :)
* Next I navigate to one of our custom static routes - /search - added by Job. 
..* I set the active theme to Portfolio -> go to  /search -> see Portfolio logo and nav bar! Great!
..* I set the active theme to careerbuildercareers theme -> go to /search -> see Portfolio logo and nav with Job's default template! WHAT?!?!?!

Debugging:
* All I have found so far is that in RequestHandler there is something called routeTheme that is set to find if the route exists in a theme. This routeTheme is then passed through as the Job plugin theme and never reset to careerbuildercareers.

Notes:
* All of my caching is turned off in my config.json
* I attaching a log on silly but Github just allow text files here so I will email you @brianhyder.
* Let me know if you want logs from a different scenario.

**Comment by cchatham** [comment] 2015-06-12 18:04
O and I am also continuing to dig but I wanted to include as much info about the issue as possible as I go.

**Comment by cchatham** [comment] 2015-06-12 19:34
Alrighty guys. Found the issue but don't know the best solution. So the routeTheme in the RequestHandler is definitely polluting the active theme. If I comment out the lines below in TemplateService everything is fine.

    TemplateService.prototype._getActiveTheme = function(cb) {
        //if (this.activeTheme) {
        //    return cb(null, this.activeTheme);
        //}
        pb.settings.get('active_theme', cb);
    };

The routeTheme is getting passed through to the BaseController as the activeTheme and therefore the TemplateService only looks at the routeTheme for a template. If I go get the activeTheme again from the database, everything is happy (of course).

I also found a second bug in TemplateService:

function TemplateService(opts){
        var localizationService;
        if (!opts || util.isFunction(opts)) {
            localizationService = opts;
            opts = {};
        }
        else {
            localizationService = opts.ls;
        }
....
}

The TemplateService constructor is not backwards compatible. The LocalizationService comes in as an object not a function so the localizationService never gets set if you only pass in the localizationService:

var aNewTempService = new TemplateSearch(theController.localizationService);

The above code results in a templateService without a localizationService. :(

**Comment by brianhyder** [comment] 2015-06-14 13:42
Thank you to everyone that provided information.  It has been enormously helpful.  In the end, poor variable naming strikes again.  In the RequestHandler on line 739 the ```onSecurityChecksPassed``` function is called.  Instead of passing the active theme.  It passes the theme that is associated with the route/controller combination that will handle the request.  

The recent changes to pass this value to the controllers and on to the template service uncovered this bug because we are no longer doing duplicate lookups for the active theme.  We started passing the value in order to drastically increase performance and reduce calls to the DB during when using a basic configuration.

I will get a fix in for this over the next couple of days.  

Thank you all again for pitching in to help get this squared away.  I will update the thread and recruit some help testing when a fix is on a branch and in place.

**Comment by brianhyder** [comment] 2015-06-16 21:48
@cchatham @JahlomP @djwhatley @evanadams28 

I have created a branch ```issues/629``` along with a commit which I *hope* will fix the issue.  Since I haven't been able to get a setup locally to test it out would y'all mind pulling it down and checking for me?

It would be greatly appreciated.

**Comment by djwhatley** [comment] 2015-06-17 01:49
@brianhyder Yup it seems to be working fine now!

**Comment by JahlomP** [comment] 2015-06-17 08:41
ok

**Comment by cchatham** [comment] 2015-06-17 12:51
I will check after my first meeting today.

**Comment by cchatham** [comment] 2015-06-17 14:19
@brianhyder looks good to me!

I am still seeing an issue with the template service not respecting the localization service i pass in. I mentioned it in my previous post. Was this intended to be a breaking change? 

My previous post I am referring to:

"I also found a second bug in TemplateService:

function TemplateService(opts){
var localizationService;
if (!opts || util.isFunction(opts)) {
localizationService = opts;
opts = {};
}
else {
localizationService = opts.ls;
}
....
}

The TemplateService constructor is not backwards compatible. The LocalizationService comes in as an object not a function so the localizationService never gets set if you only pass in the localizationService:

var aNewTempService = new TemplateSearch(theController.localizationService);

The above code results in a templateService without a localizationService. :("

Thanks again guys for this fix!!! :D

**Comment by brianhyder** [comment] 2015-06-17 14:55
I forgot about the second bug :(.  I got excited about the easy fix to the original issue.  I'll knock it out this evening and include it as part of branch mentioned above.

Thank you @cchatham for the reminder!

**Comment by cchatham** [comment] 2015-06-17 15:03
@brianhyder thank you! i appreciate all the fixes! :D

**Comment by brianhyder** [comment] 2015-06-17 21:36
@cchatham I have pushed a fix to the branch.  I will merge after green lights from Travis.

**Closed** 2015-06-19 01:35 UTC
Labels: bug
