### ISSUE TITLE
Reset password issue in admin portal

### ISSUE THREAD

**Issue by tuanvu89** [pencilblue/pencilblue#1253] opened 2017-05-23 08:41 UTC
**Description:**
An saving error always return when reset password for a user more than 2 times under admin portal.

**Steps to Reproduce:**
Go to PencilBlue admin page > Users > Manage > Select a user > Click reset password button more than 2 times.

**Configuration Details:**
N/A

**Log Output:**
N/A

PencilBlue Version: 
v8.0

Node.js Version: 
v6.10.2

Environment Description:
MacOSX El Capitan 10.11.5
![screen shot 2017-05-23 at 3 36 39 pm](https://cloud.githubusercontent.com/assets/5259432/26345620/a63aff74-3fcd-11e7-860a-15db0eff8795.png)

**Comment by dukeofsussex** [comment] 2017-05-23 08:47
Duplicate of #1248, there's already a PR open for that issue

**Comment by tuanvu89** [comment] 2017-05-23 08:50
Thanks, I was missing that report when searching

**Closed** 2017-05-23 08:49 UTC
