### ISSUE TITLE
Login page "I forgot my password" fails if there is already a pending password reset

### ISSUE THREAD

**Issue by Denal10** [pencilblue/pencilblue#1178] opened 2016-11-24 03:44 UTC
**Description:**
Query to check for a pending reset does not find any results. Using MongoDB.

**Steps to Reproduce:**
Go to login page click "I forgot my password". Then click again after email was sent. Get error failed to save due to duplicate key.

password_reset_service line 99 userObj.id needs to be userObj.id.toString()

**Configuration Details:**

**Log Output:**

PencilBlue Version: 

Node.js Version:

Environment Description:

**Comment by dukeofsussex** [comment] 2016-11-24 10:50
Duplicate of #1174

**Comment by brianhyder** [comment] 2016-12-09 17:34
See #1176

**Closed by brianhyder** 2016-12-09 17:34 UTC
Labels: duplicate, fixed in pull request
