### ISSUE TITLE
Admin panel progress dialogs don't complete

### ISSUE THREAD

**Issue by wu-lee** [pencilblue/pencilblue#1181] opened 2016-11-30 13:07 UTC
**Description:**

(Some?) progress bars in the admin panel don't complete.  However, all the ones I've tried don't seem to.

Specific cases I can recall:
* installing a new plugin
* adding a site

**Steps to Reproduce:**

With a new install of 0.7.0
* Login as admin
* Go to the admin panel, (for example) plugins->manage
* Click on the "install" button for the portfolio plugin
* Watch the progress dialog open, advance to 12%, then halt, with some log entries listed below.
* Open the Javascript console to watch continual POSTs to /api/jobs/get/<long uuid here>

50% seems to be the halt point for the other dialogs I've seen.  The dialog never closes.  Sometimes the job is completed anyway, and a reload will get past the problem, in the case of the plugin install, it does not.

An example of the dialog list content for the case of the portfolio install:

    2016-11-30T12:56:15.330Z:[1] INSTALL_PLUGIN_portfolio: Verifying that plugin portfolio is not already installed
    2016-11-30T12:56:15.334Z:[1] IS_AVAILABLE_portfolio: Updating job [f1e19381-14c2-457d-8887-62325eb6fd88:IS_AVAILABLE_portfolio] by 0 percent with status: 
    2016-11-30T12:56:15.382Z:[1] IS_AVAILABLE_portfolio: Inspecting plugin on disk at: /home/pencilblue/src/plugins/portfolio/details.json
    2016-11-30T12:56:15.419Z:[1] IS_AVAILABLE_portfolio: Updating job [f1e19381-14c2-457d-8887-62325eb6fd88:IS_AVAILABLE_portfolio] by 12 percent with status: 
    2016-11-30T12:56:15.471Z:[1] IS_AVAILABLE_portfolio: Updating job [f1e19381-14c2-457d-8887-62325eb6fd88:IS_AVAILABLE_portfolio] by 12 percent with status: 
    2016-11-30T12:56:15.530Z:[1] IS_AVAILABLE_portfolio: Updating job [f1e19381-14c2-457d-8887-62325eb6fd88:IS_AVAILABLE_portfolio] by 12 percent with status: 

**Configuration Details:**

    module.exports = {
	siteName: "<redacted>",
	siteRoot: "<redacted>",
	sitePort: 8700,
	siteIP: "127.0.0.1",
	logging: {
	    level: "debug"
	},
	db: {
	    type:"mongo",
	    servers: [
	      "127.0.0.1:27017"
	    ],
	    name: "pencilblue",
	    writeConcern: 1
	},
	cache: {
	    fake: true,
	    host: "localhost",
	    port: 6379
	},
	settings: {
	    use_memory: false,
	    use_cache: false
	},
	templates: {
	    use_memory: true,
	    use_cache: false
	},
	plugins: {
	    caching: {
		use_memory: false,
		use_cache: false
	    }
	},
	registry: {
	    type: "mongo"
	},
	session: {
	    storage: "mongo"
	},
	media: {
	    provider: "mongo",
	    max_upload_size: 6 * 1024 * 1024
	},
	cluster: {
	    workers: 1,
	    self_managed: true
	},
	multisite: {
	    enabled: true,
	    globalRoot: 'http://localhost:8700'
	}
    };

**Log Output:**

Snippet from appropriate part of log, truncated:

    {"level":"debug","message":"Response Time: 19ms URL=[POST]/api/plugins/install/portfolio CODE=200","timestamp":"2016-11-30T12:25:37.775Z"}
    {"level":"debug","message":"INSTALL_PLUGIN_portfolio: Verifying that plugin portfolio is not already installed","timestamp":"2016-11-30T12:25:37.787Z"}
    {"level":"debug","message":"IS_AVAILABLE_portfolio: Updating job [a5a0bacd-360e-4b3c-9ead-0c26ac17160b:IS_AVAILABLE_portfolio] by 0 percent with status: ","timestamp":\
    "2016-11-30T12:25:37.794Z"}
    {"level":"debug","message":"IS_AVAILABLE_portfolio: Inspecting plugin on disk at: /home/pencilblue/src/plugins/portfolio/details.json","timestamp":"2016-11-30T12:25:37\
    .863Z"}
    {"level":"debug","message":"Response Time: 10ms URL=[POST]/api/jobs/getLogs/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:37.893Z"}
    {"level":"debug","message":"IS_AVAILABLE_portfolio: Updating job [a5a0bacd-360e-4b3c-9ead-0c26ac17160b:IS_AVAILABLE_portfolio] by 12 percent with status: ","timestamp"\
    :"2016-11-30T12:25:37.913Z"}
    {"level":"debug","message":"Response Time: 7ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:37.960Z"}
    {"level":"debug","message":"IS_AVAILABLE_portfolio: Updating job [a5a0bacd-360e-4b3c-9ead-0c26ac17160b:IS_AVAILABLE_portfolio] by 12 percent with status: ","timestamp"\
    :"2016-11-30T12:25:37.980Z"} 
    {"level":"debug","message":"IS_AVAILABLE_portfolio: Updating job [a5a0bacd-360e-4b3c-9ead-0c26ac17160b:IS_AVAILABLE_portfolio] by 12 percent with status: ","timestamp"\
    :"2016-11-30T12:25:38.026Z"} 
    {"level":"debug","message":"Response Time: 21ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:39.090Z"}
    {"level":"debug","message":"Response Time: 8ms URL=[POST]/api/jobs/getLogs/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:40.006Z"}
    {"level":"debug","message":"Response Time: 7ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:40.193Z"}
    {"level":"debug","message":"Response Time: 11ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:41.302Z"}
    {"level":"debug","message":"Response Time: 18ms URL=[POST]/api/jobs/getLogs/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:42.112Z"}
    {"level":"debug","message":"Response Time: 6ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:42.404Z"}
    {"level":"debug","message":"Response Time: 6ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:43.512Z"}
    {"level":"debug","message":"Response Time: 9ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:44.625Z"}
    {"level":"debug","message":"Response Time: 19ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:45.757Z"}
    {"level":"debug","message":"Response Time: 12ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:46.867Z"}
    {"level":"debug","message":"Response Time: 5ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:47.972Z"}
    {"level":"debug","message":"Response Time: 6ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:49.070Z"}
    {"level":"debug","message":"Response Time: 6ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:50.159Z"}
    {"level":"debug","message":"Response Time: 10ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:51.275Z"}
    {"level":"debug","message":"Response Time: 17ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:52.382Z"}
    {"level":"debug","message":"Response Time: 6ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:53.472Z"}
    {"level":"debug","message":"Response Time: 6ms URL=[POST]/api/jobs/get/a5a0bacd-360e-4b3c-9ead-0c26ac17160b CODE=200","timestamp":"2016-11-30T12:25:54.590Z"}
    ...

PencilBlue Version: 0.7.0-RC1

Node.js Version: v4.6.2

Environment Description:

Debian "Wheezy" Webserver
Firefox 50.0 on Ubuntu Precise
Chomium 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit)

**Comment by dukeofsussex** [comment] 2016-11-30 13:24
I've encountered this problem pretty often as well, but the action still seems to complete correctly and is shown as done after refreshing the page.

Try using 
```
"registry": {
    "type": "redis"
}
```

I had the same issue a while back on an older version of PB and this fixed it for me.

**Comment by wu-lee** [comment] 2016-11-30 13:31
Thanks, I just tried changing the registry (it was on "mongo"), and restarting.  

Didn't seem to help.  Note, I don't have a redis server installed....  however that didn't seem to create any errors in the log output.

**Comment by dukeofsussex** [comment] 2016-11-30 13:33
No need, it uses a fake redis instance instead 😉 
Try also setting `self_managed` to `false` to see whether that makes a difference.

**Comment by wu-lee** [comment] 2016-11-30 13:37
Thanks, tried that too, both with and without the registry change.  No difference...

**Comment by dukeofsussex** [comment] 2016-11-30 14:02
Okay, I can confirm that it's a bug with the plugin installation procedure when installing plugins globally.

To start off with, the job's `log` window receives an `undefined`, which causes it to close and the page to refresh.

Sadly, after running into the same issue as you @wu-lee it somehow managed to fix itself and I'm able to install plugins globally again. The only thing I remember doing was clearing the `job_log` and `job_run` collections.

@wu-lee: Have you got a tool to inspect your db installed? If so, could you see whether either of the `job_` collections contains a document with only **2** fields?

**Comment by wu-lee** [comment] 2016-11-30 15:01
I'm new to mongodb, but I see something called mongoexport.  Exporting the job_log and job_run collections doesn't seem to find any documents with only two fields, but then some of these JSON attributes may be special and not "fields" in your terminology.

job_log's docs all have 9 fields, job_run's docs all have 7 except for one.  These vary.  What should I look for, specifically?

Poking around in the source in the meantime.

**Comment by dukeofsussex** [comment] 2016-11-30 15:13
Sadly I don't know. My db had 2 documents with only 2 fields each and after deleting those it worked, so I thought that maybe something had been written incorrectly, but that was probably a one-off, as I haven't been able to reproduce it

**Comment by wu-lee** [comment] 2016-11-30 15:55
Actually it has 8, and appears to be to do with altering a site's details:

    {
      "_id": "a3d50508-21b7-4688-b8de-6a346070d611",
      "error": null,
      "id": "a3d50508-21b7-4688-b8de-6a346070d611",
      "last_modified": {
	"$date": 1480378664430
      },
      "name": "EDIT_SITEcbd652d2-bee6-4e13-9ac3-bef4952da151",
      "object_type": "job_run",
      "progress": 100,
      "status": "COMPLETED"
    }

The others vary, on inspection, and include jobs for other admin panel task. A more relevant case:

    {
	"_id": "f1e19381-14c2-457d-8887-62325eb6fd88",
	"id": "f1e19381-14c2-457d-8887-62325eb6fd88",
	"last_modified": {
	  "$date": 1480510575329
	},
	"name": "INSTALL_PLUGIN_portfolio",
	"object_type": "job_run",
	"progress": 37.5,
	"status": "RUNNING"
    }

That's the last one in the list, although TBH I did't check their chronology.

**Comment by dukeofsussex** [comment] 2016-11-30 16:05
Yeah, nothing wrong with either. I'll have a look into it the next few days.

**Comment by brianhyder** [comment] 2016-11-30 21:31
We've had a couple of reports of this over a few versions.  The *majority* of the time it is due to users leveraging mongo as the registry provider and then restarting faster than once per minute.  Mongo cannot expire documents faster than that, unlike redis so sometimes you have stale registry entries that represent processes that no longer exist.

Aside from that, I'm not sure what you are experiencing.  Checking to see if a real redis instance fixes the issue would be good.  It could always be an issue with an underlying module (fake-redis) or the mongo driver.  Although, there have only been a few exceptions where it was the third party and not PB.

**Comment by wu-lee** [comment] 2016-11-30 21:44
Thanks - is there an explanation of what the registry is and how it relates to the progress bar anywhere?

**Comment by wu-lee** [comment] 2016-12-01 09:53
Unpicking the code from the tagged commit 0.7.0-RC1... observing that I see the log entries shown above, operations which have definitely contributed something:
- PluginInstallJob.getInitiatorTasks()
  - task 0: emits "Verifying that..."
  - task 1: calls PluginAvailableJob() emitting "Inspecting plugin on disk...."
    - task 0: calls .doUpdate() emitting "Updating job..."
  - task 2: calls .doPersistanceTasks()
    - task 0: should emit "Loading details file for ..."

However I don't see that last message logged.  So I think it must be halting before it reaches that step.

My initial suspicion is something is going wrong in the async.series() call on line 212 of plugin_install_job.js, which is the part of .doPersistenceTasks() which runs the tasks whose output I don't see.  The only thing before the missing log message is a call to PluginService.getDetailsPath() on line 152, which looking it up, seems just to do a string concatenations, so no chance of a hold up there unless there's an exception, which I assume I'd see logged...

At this point, my knowledge of NodeJS falters, I will have to go and read up on what might go wrong here.  I'm hoping this will give a clue to someone more familiar than I.

But, I don't see any mentions of "the registry" in the code path so far, or anything obviously connected.  If it were something to do with registry/timestamping resolution, wouldn't I expect to see timestamps which exhibit this problem (however it manifests) in the logs?

**Comment by wu-lee** [comment] 2016-12-01 11:44
Hold on. I just checked the package.json of the code I was looking at, which says:

    "version": "0.6.1"

And yet, I double checked, and it really is 0.7.0-RC1 I have checked out. 

I picked the tag 0.7.0-RC1 because my pencilblue-cli experiment installed code with a package.json reporting "0.7.0", and this was the closest. There is no branch named 0.7.0, and no other 0.7 series tag superceding it, so it does seem a reasonable assumption.

The reason I am installing from git is that pencilblue-cli isn't amenable to automation - it prompts the user to input various things interactively.

Now I am wondering, am I using the correct version if I want stable, working code?

**Comment by brianhyder** [comment] 2016-12-01 13:07
@wu-lee 

You can find some documentation about how the clustering and registry works under the "Getting Ready for Production" section: https://github.com/pencilblue/pencilblue/wiki/Quickstart:-Configuration
The registry essentially provides a record of each instance of PB running in the cluster.

Our master branch and tags are meant to be stable.  Albeit that the RC tags sometimes have flaws.  I must have forgot to push the final tag for 0.7.0.  That is my fault.  After @dukeofsussex's PR gets merged (hopefully, this weekend) I'll be cutting a tag for 0.7.1 that is meant to be stable.

Have you adjusted the log level to "silly"?  At that level you will be able to see the requests sent from one instance of PB to another via the configured command service broker.  By default, this should be the fake redis instance.

**Comment by wu-lee** [comment] 2016-12-01 15:51
Ok, so I've upgraded to the head of master (), and put the log-level to "silly".

Initially clicking the plugin install button did a similar thing to before, except this time it closed instead of sitting there.  Nothing installed however, and there wasn't really any time to see what the messages where. I did notice the last line  was "undefined", just before the page reloads. I repeated this several times, same  result.

Checking the log, however, I find this, which looks like an attempt to contact the registry:

    {"Level":"silly","message":"RequestHandler: Comparing Path [/api/plugins/install/portfolio] to Pattern [^/api/plugins/[^/]+/[^/]+[/]{0,1}$] Result [true]","timestamp":"2016-12-01T14:49:12.426Z"}
    {"level":"silly","message":"SettingService15: Checking Service [DB-cbd652d2-bee6-4e13-9ac3-bef4952da151-false] for key [active_theme]","timestamp":"2016-12-01T14:49:12.427Z"}
    {"level":"silly","message":"RequestHandler: Settling on theme [pencilblue] and method [POST] for URL=[POST:/api/plugins/install/portfolio]","timestamp":"2016-12-01T14:49:12.432Z"}
    {"level":"silly","message":"SettingService1: Checking Service [DB-global-false] for key [system_initialized]","timestamp":"2016-12-01T14:49:12.432Z"}
    {"level":"silly","message":"RequestHandler: Security Result=[true] - {\"checkSystemSetup\":{\"success\":true},\"checkRequiresAuth\":{\"success\":true},\"checkAdminLevel\":{\"success\":true},\"checkPermissions\":{\"success\":true}}","timestamp":"2016-12-01T14:49:12.434Z"}
    {"level":"debug","message":"Response Time: 20ms URL=[POST]/api/plugins/install/portfolio CODE=200","timestamp":"2016-12-01T14:49:12.437Z"}
    {"level":"debug","message":"INSTALL_PLUGIN_portfolio: Verifying that plugin portfolio is not already installed","timestamp":"2016-12-01T14:49:12.457Z"}
    {"level":"debug","message":"IS_AVAILABLE_portfolio: Updating job [05eb7a65-ee2a-4853-8bd6-b613d50fc091:IS_AVAILABLE_portfolio] by 0 percent with status: ","timestamp":"2016-12-01T14:49:12.465Z"}
    {"level":"silly","message":"RedisCommandBroker: Sending command [<redacted>:8700:1:<redacted>]{\"jobId\":\"05eb7a65-ee2a-4853-8bd6-b613d50fc091\",\"pluginUid\":\"portfolio\",\"to\":\"<redacted>:8700:1:<redacted>\",\"from\":\"<redacted>:8700:M:<redacted>\",\"type\":\"is_plugin_available\",\"date\":\"2016-12-01T14:49:12.469Z\",\"id\":\"6faef6d8-e8bf-4144-81a4-e68d31efb079\"}","timestamp":"2016-12-01T14:49:12.469Z"}
    {"level":"silly","message":"New Request: 37231cb6-93f6-48b1-b03f-b10ff6187445","timestamp":"2016-12-01T14:49:12.521Z"}
    {"level":"silly","message":"RequestHandler: Session ID [1893b522-bd71-427d-adae-e6a33c28fc7f] Cookie SID [1893b522-bd71-427d-adae-e6a33c28fc7f] Created [false] Expired [false]","timestamp":"2016-12-01T14:49:12.523Z"}
    {"level":"silly","message":"RequestHandler: Comparing Path [/api/jobs/getLogs/05eb7a65-ee2a-4853-8bd6-b613d50fc091] to Pattern [^/media/.*[/]{0,1}$] Result [false]","timestamp":"2016-12-01T14:49:12.523Z"}

It says "Sending command", and grepping the source I see there are two matches, one in RedisCommandBroker (as tagged here), and one from MongoCommandBroker.

So, my server was configured to use:

    registry: {
        type: "mongo"
    },

This makes me wonder why the RedisCommandBroker is reported in the logs? Could this be the source of the bug, some sort of failure to configure the broker correctly?

The obvious next step is to try "redis" as @dukeofsussex suggested.  And... now the install button works.

Switching back to "mongo": installing the "wp_import" fails.  Uninstalling "porfolio" ... works (with that final "undefined" line in the dialog).  Reinstalling "portfolio" fails. Repeatedly.

Restoring "redis":  now it works again. (There is that final "undefined" still).

(Aside: changing the "self_managed" setting as also suggested by @dukeofsussex doesn't seem to make any difference.)

So I conclude it is something to do with the "mongo" broker, and there is no mention of the MongoiCommandBroker in the logs at any point.

**Comment by brianhyder** [comment] 2016-12-01 15:57
Side Note:
When you pull updated code make sure to ```npm install``` to ensure that you have the latest modules used for the release.

It is possible to mix and match command brokers and registry providers.  The registry is the mechanism to know which instances are available while the command broker implementation determines which service to use as the communication channel between instances.

If you query the "registry" collection in your mongo DB you should only see at most two records.  If you are running in self managed mode then I would expect to see two records.  One that represents the master process and one that represents the worker process.  When self managed mode is off then I would expect a single entry.  If you have more records in that collection than expected then it means you are running into the issue I initially commented on where the records are not expiring from mongo fast enough.

**Comment by brianhyder** [comment] 2016-12-01 16:05
Based on the logs you provided I'm guessing the records didn't expire.  My reasoning is because of the log entry where the master process is attempting to send a message to the worker process with worker ID=1.  This would only happen if you were first running in self managed mode then stopped PB and restarted with self managed mode off in less than 60 seconds.  When you restarted, the old worker process record was still in mongo and the master process assumed that the old worker process was active.  It tried to send a message to the old process and timed out waiting for a response because it was not active.  Therefore the install cannot complete.

SIDE NOTE: you cannot run in self managed mode, with more than 1 worker, and use fake redis.  The reason is because the fake redis runs in memory.  The memory spaces for the different worker processes are not sharable and therefore would not be able to communicate with one another using the redis command broker.

**Comment by wu-lee** [comment] 2016-12-01 16:10
After more poking around... I can see by inserting traces in the code that this seems right: the command broker is always set to RedisCommandBroker, and the config it gets is always "redis".

This is because there are two cases in point here.  The one I have been changing, from the examples, is for the registry:

    registry: {
        type: "mongo"
    },

And the one which sets the command broker is absent from the config example I used, so always has the default (although PB supports "mongo" and "redis" as built-in implementations):

    command: {
        broker: "redis"
    },

If I add the latter,and set it to "mongo", I do get the MongoCommandBroker tagged in the logs (so both broker and registry are "mongo").  However, this doesn't appear to fully work - the progress dialogs appear and disappear, but the plugins don't get installed.  I don't know why, except I do notice this line in the logs

    2016-12-01T15:59:59.791Z - silly: [1] MongoCommandBroker: A message was received for channel [<redacted>:8700:2:<redacted>] but no handler was available to accept it. This is most likely normal

So: at least the "redis" registry works for me now, and the progress dialogs don't hang around forever.  And I can make some progress. But I think there is still something going wrong in PB's job runner.

**Comment by wu-lee** [comment] 2016-12-01 16:19
@brianhyder - thanks, read your reply after leaving my last.

Regarding self-managed mode, noted - however I don't actually know what that means, so I don't fully understand your explanation beyond "don't do that!".   I don't recall the docs mentioning it, and I only changed that setting back to the default given on the [multi-tenancy guide](https://github.com/pencilblue/pencilblue/wiki/Multi-Tenancy) because I'd changed it to false on a suggestion from @dukeofsussex earlier.

It is quite possible I stopped, change this and then restarted in less than 60 seconds.  I am unsure if that affects my reasoning above.

**Comment by wu-lee** [comment] 2016-12-01 16:23
And just to confirm, I did run 'npm install' after updating, thanks.

**Comment by brianhyder** [comment] 2016-12-01 19:09
Good, I'm glad you have a working solution, at the moment.  There are definitely a few improvements that need to be made around the mongo registry provider.  I'll add those to the list for the 1.0 release, coming in March/April timeframe as well as updates for the documentation.  

For reference, in the meantime, the self managed mode leverages the Node.js ```cluster``` module.  The module allows PB to load balance across all of the cores on a server.  When self managed mode is true a master process is started along with some number of workers.  The default configuration uses 1 but it can be set to whatever makes sense.  It can also be set to "auto" and will then detect the number of cores on your processor and create a worker for each one.  When the self managed mode is off then only a master process starts.  This is used most often in elastic environments like openshift, beanstalk, or heroku.

I am closing this issue but please feel free to reach out here or on Gitter with any additional questions.  We're happy to help

**Closed** 2016-12-01 19:09 UTC
Labels: help wanted, question
