### ISSUE TITLE
post.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#1078] opened 2016-06-27 14:54 UTC
**Description**
post.hasOwnProperty is not a function error occurs during admin signup on initial installation

**Steps to Reproduce:**
Installation process  during admin signup submit

**Log Output** 
`TypeError:` post.hasOwnProperty is not a function
    at Function.DocumentCreatorModule.DocumentCreator.passwordHash (/home/jahlom/jahlom/include/model/create_document.js:85:18)
    at Function.DocumentCreatorModule.DocumentCreator.create (/home/jahlom/jahlom/include/model/create_document.js:51:25)
    at /home/jahlom/jahlom/plugins/pencilblue/controllers/actions/setup.js:121:55
    at /home/jahlom/jahlom/node_modules/async/lib/async.js:610:21
    at /home/jahlom/jahlom/node_modules/async/lib/async.js:249:17
    at iterate (/home/jahlom/jahlom/node_modules/async/lib/async.js:149:13)
    at async.eachSeries (/home/jahlom/jahlom/node_modules/async/lib/async.js:165:9)
    at _asyncMap (/home/jahlom/jahlom/node_modules/async/lib/async.js:248:13)
    at Object.mapSeries (/home/jahlom/jahlom/node_modules/async/lib/async.js:231:23)
    at Object.async.series (/home/jahlom/jahlom/node_modules/async/lib/async.js:608:19):`

PencilBlue Version: 0.5.1

Node.js Version: 6.2.2

Environment Description: Ubuntu 14.04

**Comment by brianhyder** [comment] 2016-06-27 15:40
This should be fixed in 0.6.0 and the master branch

**Comment by brianhyder** [comment] 2016-06-28 12:37
@JahlomP can you confirm that the issue is resolved in the master branch?

**Closed** 2016-07-05 16:30 UTC
Labels: help wanted, question
