### ISSUE TITLE
Installing a plug in with dependencies

### ISSUE THREAD

**Issue by amirsaber** [pencilblue/pencilblue#828] opened 2015-11-11 18:38 UTC
When I install a plugin with dependencies, the front end never finish installing, while the installation is finished, I noticed a message keeps getting send to server and on server I got this error
```
2015-11-11T18:36:40.541Z - warn: [M] CommandService: The command was in reply to [d2d2053f-4ccf-4bb6-983d-50ecc803b29c] but no callback was registered. Skipping.
```

**Comment by brianhyder** [comment] 2015-11-11 18:43
Are you working against the master branch or against 0.5.0?  This is npm
taking longer to complete than the allowed time. Look at adjusting the
command timeout by overriding it in your config.js file.

**Comment by brianhyder** [comment] 2015-11-11 18:46
This is a duplicate of #792

**Comment by amirsaber** [comment] 2015-11-11 18:48
oh sorry, you are totally right, I am working on 0.4.0. Thanks

**Closed** 2015-11-12 02:44 UTC
Labels: duplicate
