### ISSUE TITLE
Error on updating article

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#523] opened 2015-04-02 17:56 UTC
I get a server error on updating articles. v0.4.0. Can someone verify and let me know if i'm the only one getting this error or is a bug.

**Comment by JahlomP** [comment] 2015-04-03 11:13
![untitled](https://cloud.githubusercontent.com/assets/4746511/6981517/42c2b0d8-d9f2-11e4-9fe1-98ce832f8786.png)

I'm getting existing url error when updating but this is the only article in the system.

**Comment by JahlomP** [comment] 2015-04-03 11:13
@brianhyder @blakecallens  a little help here.

**Comment by blakecallens** [comment] 2015-04-03 17:22
Not happening on my end with the latest version of master.

**Comment by brianhyder** [comment] 2015-04-03 22:25
I was able to reproduce.

1) click new article
2) fill in title: "hello"
3) fill in custom URL: "wo-wo"
4) fill in content: "hello world"
5) click "Save Draft"

The draft appears to save.  However, afterwards if I click "Preview" nothing happens.  

6) Click articles in the nav menu
7) Select the article you just drafted
8) Click "Preview"

**Comment by vqoph** [comment] 2015-04-04 01:42
i've got this in the devtools console : 

    XHR finished loading: POST "http://localhost:8080/actions/admin/content/articles/551f3f49a22eee585d488f65"
    POST http://localhost:8080/actions/admin/content/articles/551f3f49a22eee585d488f65 400 (Bad Request)

and this in the  logfile  

    1214  {"level":"warn","message":"DAO: getNotIDField is deprecated. Use getNotIdField instead","timestamp":"2015-04-04T01:35:01.433Z"}
    1215: {"level":"debug","message":"Response Time: 5ms URL=[POST]/actions/admin/content/articles/551f3f49a22eee585d488f65 CODE=400","timestamp":"2015-04-04T01:35:01.434Z"}

**Comment by qbanguy** [comment] 2015-04-08 22:19
I'm seeing the same error when creating a new article.

**Comment by blakecallens** [comment] 2015-04-13 12:49
@brianhyder the reason *Preview* did nothing for me is because the popup was blocked by the browser. We have to do a ```window.open()``` call after the draft is saved, so you might have to allow popups to see it.

@JahlomP I recreated your screenshot and the article saved fine on both the new and edit screens.

@qbanguy the EXISTING_URL error (we need to add a localization key for that) means that another item in the system is already using that URL. Are you sure there's no other page, article, or section using the same URL key?

**Comment by qbanguy** [comment] 2015-04-14 21:58
@blakecallens Fresh new install and started adding an article. I input the url and then go to the next field, write something in the body and click save. Errors out giving Existing URL... Sometimes it works sometimes it doesn't.

**Comment by victorkane** [comment] 2015-04-15 23:48
What's happening is that the article IS saved. And then the screen should clear or something, because when you click SAVE again, it thinks you are creating a new article from zero, the interface doesn't "know" you want to update. When you go somewhere else in admin thus effectively clearing the form, and then go to content and go to update the article everything works fine and you are able to update.

So the "bug" is that upon saving a new article, the form is still in a POST state instead of a PUT state or something like that.

**Comment by qbanguy** [comment] 2015-04-16 02:11
@victorkane you nailed it. I feel that the same behavior/bug is happening on other sections.

**Comment by blakecallens** [comment] 2015-04-16 02:15
So it looks like the bug is that the redirect to the edit article screen isn't always happening after saving a new article. I'll take a look at the Angular controller tomorrow and see if I can find a fix.

**Comment by victorkane** [comment] 2015-04-16 02:28
Looking forward to learning more about PencilBlue architecture so I can help out instead of just reporting :)

**Comment by qbanguy** [comment] 2015-04-16 02:32
Great! I really like the approach that pencilblue has taken, hopefully I can contribute on making it better.

**Comment by blakecallens** [comment] 2015-04-16 13:04
I've tried a every possible way to reproduce this, and I haven't seen this happen once. I'll need some more info from you guys to be able to track it down.

1. When you initially create the article and hit Save, are you taken to a page where the top now says, "Edit [article name]"?
2. If you're not taken to the Edit page, are there any JS console errors? Can it be something with your browser where ```window.location``` is being blocked?
3. If you are taken there, can you trace your network output from the *edit* REST call to the controller? I want to see if the call is going to the wrong place.

@brianhyder, if you can reproduce, let me know.

**Comment by victorkane** [comment] 2015-04-16 13:27
* Go to Content > Articles, hit "+"
* Enable Chrome console (MacBook Air Yosemite, normal Chrome current version)
* nodemon output visible 
* Fill in all Article fields
* On Save draft button, click up arrow and click on Save
* Green message on top of page says "Test was created"
* New article shows up just fine on home page, so it was saved fine.
* Console shows javascript error:

````
TypeError: Cannot read property 'toString' of undefined
    at new:915
    at angular.js:7733
    at H (angular.js:11100)
    at H (angular.js:11100)
    at angular.js:11186
    at h.$eval (angular.js:12175)
    at h.$digest (angular.js:12004)
    at h.$apply (angular.js:12279)
    at g (angular.js:7991)
    at C (angular.js:8196)
````

* nodemon shows no output
* There is no page redirect to anywhere, path still `/admin/content/articles/new`
* I make a change in the sub heading
* I save article again (button still says Save draft, so I just hit that).
* Red EXISTING_URL error message appears on top of screen
* Refresh of home page shows that article NOT updated.
* Javascript console shows POST 400 bad request
* Go back to articles, click on the newly created article, am effectively at Edit {article name} page
* Button at the bottom says Save, I hit it after changing sub heading
* No errors, Green Test was edited appears fine
* Nothing on javascript console, but we get some warnings from nodemon:

````
2015-04-16T13:25:37.809Z - warn: [1] DAO: getNotIDField is deprecated. Use getNotIdField instead
2015-04-16T13:25:37.810Z - warn: [1] DAO: getNotIDField is deprecated. Use getNotIdField instead
````

* Refresh of home page shows correctly modified article.

Hope that helps :)

**Comment by blakecallens** [comment] 2015-04-19 17:28
It looks like what's happening (which I still can't reproduce) is the object returned from the new article save doesn't have an ID field. Because of this, the toString call that appends that new ID to the $window.location, sending you to the edit page, is breaking.

I'm putting in a failsafe/backstop here. If there's no ID field, then you'll be rerouted to the articles list page. That will at least keep you from unknowingly editing things and not being able to save.

**Comment by brianhyder** [comment] 2015-04-19 18:48
After some digging here is what has occurred.  As part of the 0.4.0 release we upgraded the mongo driver to 2.0.x.  What we have overlooked what that the new driver breaks contract on what is returned after a save command.  This has resulted in breakages in the UI because the ```_id``` is not available on the returned result.  

We are actively working to update the core codebase to keep the expected contract.

**Comment by brianhyder** [comment] 2015-04-19 21:20
Ok all, I've just committed a fix that I *think* will take care of the issue that y'all are seeing.  I'm going to leave this open for a few days so everyone has a chance to take a look and leave feedback.  Sorry again for all of the confusion.

**Comment by qbanguy** [comment] 2015-04-19 23:11
I'm getting a mongodb error when running it. 

```pencilblue/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error
    at Object.<anonymous> (/IO/pencilblue/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:42:24)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/IO/pencilblue/node_modules/mongodb/node_modules/mongodb-core/index.js:2:17)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)```

**Comment by JahlomP** [comment] 2015-04-19 23:15
Me too. I just updated pb but still getting it.

**Comment by blakecallens** [comment] 2015-04-19 23:24
Did you run an ```npm update```? I think that might fix your issue.

**Comment by brianhyder** [comment] 2015-04-19 23:43
Can you guys please send us the following:

1. the version of mongo you are running
2. the version of the mongodb driver that you have in the node_modules directory of your PB installation
3. Steps to reproduce 
4. Confirm that doing an ```npm update``` does not correct any issues

I have just walked through:
* creating a new article and saving as a draft
* creating a new article and saving as published
* editing an article
* editing a draft

I can't seem to get any error.

**Comment by victorkane** [comment] 2015-04-20 00:14
Passes with flying colors for me.

1. Fresh install of pencilblue at http://awebfactory.net:8080/  (Ubuntu 12.04.5 on digital ocean, mongodb version v2.4.13, node version 0.10.38)
2. Create new article, save draft, correctly redirects to edit article, save to publish, no error, correctly redirected to edit article
3. Create second article, directly use save instead of save draft, correctly saved, correctly redirected to edit article
4. Create third article, hit save draft, successfully redirected to edit mode, changed to save button, hit save, green message at top: "Yet a third incursion on the same subject was edited", edited body directly, no error.
5. All three articles appear at http://awebfactory.net:8080/

Will leave this running on nodemon for another couple of hours.

**Comment by qbanguy** [comment] 2015-04-20 01:31
My bad guys, my local mongo instance wasn't running. I went over the
creation/update of an article/page and works perfectly.

P.S. I'm using iojs 1.3

On Sun, Apr 19, 2015 at 5:14 PM, Victor Kane <notifications@github.com>
wrote:

> Passes with flying colors for me.
>
>    1. Fresh install of pencilblue at http://awebfactory.net:8080/ (Ubuntu
>    12.04.5 on digital ocean, mongodb version v2.4.13, node version 0.10.38)
>    2. Create new article, save draft, correctly redirects to edit
>    article, save to publish, no error, correctly redirected to edit article
>    3. Create second article, directly use save instead of save draft,
>    correctly saved, correctly redirected to edit article
>    4. Create third article, hit save draft, successfully redirected to
>    edit mode, changed to save button, hit save, green message at top: "Yet a
>    third incursion on the same subject was edited", edited body directly, no
>    error.
>    5. All three articles appear at http://awebfactory.net:8080/
>
> Will leave this running on nodemon for another couple of hours.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/523#issuecomment-94327456>
> .
>



-- 
ciao
Adrian

**Comment by JahlomP** [comment] 2015-04-20 04:49
I did not do npm update myself. Sorry.

On Monday, April 20, 2015, Adrian Sanchez del C. <notifications@github.com>
wrote:
> My bad guys, my local mongo instance wasn't running. I went over the
> creation/update of an article/page and works perfectly.
>
> P.S. I'm using iojs 1.3
>
> On Sun, Apr 19, 2015 at 5:14 PM, Victor Kane <notifications@github.com>
> wrote:
>
>> Passes with flying colors for me.
>>
>> 1. Fresh install of pencilblue at http://awebfactory.net:8080/ (Ubuntu
>> 12.04.5 on digital ocean, mongodb version v2.4.13, node version 0.10.38)
>> 2. Create new article, save draft, correctly redirects to edit
>> article, save to publish, no error, correctly redirected to edit article
>> 3. Create second article, directly use save instead of save draft,
>> correctly saved, correctly redirected to edit article
>> 4. Create third article, hit save draft, successfully redirected to
>> edit mode, changed to save button, hit save, green message at top: "Yet a
>> third incursion on the same subject was edited", edited body directly, no
>> error.
>> 5. All three articles appear at http://awebfactory.net:8080/
>>
>> Will leave this running on nodemon for another couple of hours.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <
https://github.com/pencilblue/pencilblue/issues/523#issuecomment-94327456>
>> .
>>
>
>
>
> --
> ciao
> Adrian
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/jkchTW8XUmENuBV274_tpWvgdMknjfVK9sBBy1uP8K_vv6bJU1aODa3kBEHv5JpwJ3vCm-zaJecuVhyBKiioAoc0TCrbTarB1mb2N9IMXc_kUNZTYucfsKwJuMw5e6GiiBYg6ZsWXjMbKXs-TmfQBcvvGuyyiQ=s0-d-e1-ft#https://github.com/notifications/beacon/AEhtD_77_qvn7wO3nI_YwdVYG04Q7o2-ks5oBE5mgaJpZM4D5VM1.gif
>

-- 
Best Rregards,
Precious Jahlom Agboado,
NibbleIT,
www.twitter.com/jahlomp
+233 54 0915 108.

**Comment by brianhyder** [comment] 2015-04-25 21:30
Looks like this is now a non-issue since the DAO change and dependency update.  I'm closing but if anyone encounters issues again let me know.

**Closed by brianhyder** 2015-04-25 21:30 UTC
Labels: can't reproduce, help wanted
