### ISSUE TITLE
Manage Article view

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1161] opened 2016-10-15 14:14 UTC
**Description:**
Multisite : enabled.
You can add an article, but when you retur to view or select again manage article view, the following error is flashing:
 E11000 duplicate key error collection: pencil_blue.setting index: key_1 dup key: { :
 "content_settings"}
 if you pick f12 on chrome:
Failed to load resource: the server responded with a status of 11000 (unknown)

PencilBlue Version: "version": "0.7.0",

Node.js Version: 5.10.1

MongoDB: 3.2.4

**Comment by dukeofsussex** [comment] 2016-10-15 14:16
Duplicate of https://github.com/pencilblue/pencilblue/issues/1160, as both services work simalarly

**Closed** 2016-10-18 12:50 UTC
Labels: bug, duplicate, in progress
