### ISSUE TITLE
Not able to write articles or switch sites in 0.6.0

### ISSUE THREAD

**Issue by JLKM** [pencilblue/pencilblue#1056] opened 2016-05-18 23:09 UTC
The present PB 0.6.0-branch on Node.js 6.X seems to behave different on my multisite installations on my local Windows-laptop installation (localhost) and on my QNAP/Linux-server (192.168.1.97:8082).

On the local installation everything works fine. From Manage Sites I can click on the links and switch between sites and write articles.

On my server-installation, however, I can neither switch sites - nor write articles on the basic site. Atttempting to switch site I do get the "Authentication Token Created" - but not the "Successfull login", and the link takes me nowhere.

At the main site I'm able to create containers, sections and topics. But nothing happens, when I try to save media-docs, articles or pages.

As shown below MongoDB actually saves the elements mentioned, but the rest dissapear. A copy of the config.js on the server is also added.

Have I missed something, or is it a bug?

*****

MongoDB-log:

> show dbs                                                                                                                     
local   0.00006866455078125GB
pencilblue      0.001300811767578125GB
> use pencilblue                                                                                                               
switched to db pencilblue
> db.topic.find()                                                                                                              
{ "_id" : ObjectId("573cee3bcfc876bb603c59eb"), "name" : "Testemne", "site" : "e6127075-895a-485e-ad92-9c6ec951a4ea", "object_t
ype" : "topic", "created" : ISODate("2016-05-18T22:35:39.218Z"), "last_modified" : ISODate("2016-05-18T22:35:39.218Z") }
> db.section.find()                                                                                                            
{ "_id" : ObjectId("573cedb0cfc876bb603c59e8"), "type" : "container", "name" : "Dropdown1", "keywords" : [ ], "parent" : null, 
"object_type" : "section", "url" : null, "editor" : null, "item" : null, "link" : null, "new_tab" : null, "site" : "e6127075-89
5a-485e-ad92-9c6ec951a4ea", "created" : ISODate("2016-05-18T22:33:20.510Z"), "last_modified" : ISODate("2016-05-18T22:33:20.510
Z") }
{ "_id" : ObjectId("573cee08cfc876bb603c59ea"), "type" : "section", "name" : "Menu 1.1", "parent" : "573cedb0cfc876bb603c59e8",
 "url" : "menu-1-1", "editor" : "573ce9e6e8d073b65988f868", "keywords" : [ ], "object_type" : "section", "item" : null, "link" 
: null, "new_tab" : null, "site" : "e6127075-895a-485e-ad92-9c6ec951a4ea", "created" : ISODate("2016-05-18T22:34:48.274Z"), "la
st_modified" : ISODate("2016-05-18T22:34:48.274Z") }
> db.article.find()                                                                                                            
> db.page.find()                                                                                                               
> db.site.find()                                                                                                               
{ "_id" : ObjectId("573ce61db5f10b2551f6e109"), "displayName" : "pbtest", "hostname" : "192.168.1.97:8082", "object_type" : "si
te", "active" : true, "uid" : "e6127075-895a-485e-ad92-9c6ec951a4ea", "supportedLocales" : null, "defaultLocale" : null, "prevH
ostnames" : [ ], "created" : ISODate("2016-05-18T22:01:01.138Z"), "last_modified" : ISODate("2016-05-18T22:19:28.986Z") }
{ "_id" : ObjectId("573cea1be8d073b65988f86c"), "displayName" : "Typescript", "hostname" : "typescript.192.168.1.97:8082", "def
aultLocale" : "en-US", "supportedLocales" : { "en-US" : true }, "object_type" : "site", "active" : true, "uid" : "53a34b63-3f29
-4915-a8ad-2a5a6387d4e4", "prevHostnames" : [ ], "created" : ISODate("2016-05-18T22:18:03.175Z"), "last_modified" : ISODate("20
16-05-18T22:19:23.528Z") }
{ "_id" : ObjectId("573cea35e8d073b65988f86f"), "displayName" : "NodeJS", "hostname" : "nodejs.localhost:8082", "defaultLocale"
 : "en-US", "supportedLocales" : { "en-US" : true }, "object_type" : "site", "active" : true, "uid" : "bb8170b6-01b1-4c87-b313-
4deff5924d00", "prevHostnames" : [  "nodejs.192.168.1.97:8082" ], "created" : ISODate("2016-05-18T22:18:29.762Z"), "last_modifi
ed" : ISODate("2016-05-18T22:25:24.047Z") }                                                                                    
>                                                                                                                              
*****

Config.js on server:
(Have also tried: "globalRoot": "http://192.168.1.97:8082")

module.exports = {
    "siteName": "pbtest",
    "siteRoot": "http://192.168.1.97:8082",
    "sitePort": 8082,
    "logging": {
        "level": "info"
    },
    "db": {
        "type": "mongo",
        "servers": [
            "mongodb://127.0.0.1:27017/"
        ],
        "name": "pencilblue",
        "writeConcern": 1
    },
    "cache": {
        "fake": true,
        "host": "localhost",
        "port": 6379
    },
    "settings": {
        "use_memory": false,
        "use_cache": false
    },
    "templates": {
        "use_memory": true,
        "use_cache": false
    },
    "plugins": {
        "caching": {
            "use_memory": false,
            "use_cache": false
        }
    },
    "registry": {
        "type": "mongo"
    },
    "session": {
        "storage": "mongo"
    },
    "media": {
        "provider": "mongo",
        "max_upload_size": 6291456
    },
    "cluster": {
        "workers": 1,
        "self_managed": true
    },
	"multisite": {
        "enabled": true,
        "globalRoot": "http://global.192.168.1.97:8082"
    },
    "siteIP": "192.168.1.97"
};

**Comment by brianhyder** [comment] 2016-05-28 21:06
I'm not sure that we've ever tried to setup sites based on IP addresses.  It was meant to be domain name based.  Have you had any luck lately getting it to work for you?

**Comment by JLKM** [comment] 2016-05-29 06:08
No, I've paused it in favour of tests with NodeBB and Telescope. I still would like the opportunity to test on a server behind a firewall - before opening up for the net and web-adresses without ip-addresses. Any suggestions? Nginx?
Anyway. Isn't it strange, that - with ip-addresses - I'm able to create containers, sections and topics? Only media-docs, articles or pages will not save...

**Comment by markbaird** [comment] 2016-05-29 16:14
You should be able to test using domains behind your firewall by setting up those domains in your workstation's hosts file.

**Comment by blakecallens** [comment] 2016-05-29 16:17
Looks like this is because those pages were switched over to being API
driven. This will become a universal issue when the admin-update branch is
merged in. We should look for a long term solution, because someone might
want to host by IP.

**Comment by JLKM** [comment] 2016-05-29 18:36
Don't forget your wives during the weekend both of you... just kidding. Thank you very much for your quick answers. Since the IP-URL-issue apparently is only going to grow, I'll stick with that hosts file. I appreciate PencilBlue big time. Multi-tenancy and multi-language really rocks. So does the fusion of categories/subcategories and dropdowns. Can only think of a missing third workflow stage on documents. Perhaps Unpublished in addition to Draft and Published.

**Comment by brianhyder** [comment] 2016-05-30 18:24
@JLKM haha, no worries.  Just wanted to give you a heads up that I was able to reproduce this on 0.6.0.  I'll be looking into it this week.

Steps to reproduce:
1. Configure new multi-site instance with unused db name, multisite: true, globalRoot: 'http://localhost:8080', 
2. Go through setup
3. Add child site in admin section 127.0.0.1:8080
4. Navigate back to manage sites
5. Activate deactivated main site (not sure why this shows as deactivated.  I think this is the part that's broken)
6. Click on the activated main site to initiate transfer to that site

The notification indicating that the token was created appears but nothing else happens.  However, the browser console produces the following:
```
Failed to load resource: the server responded with a status of 400 (Bad Request)
angular.js:9563 TypeError: Cannot read property 'message' of undefined
    at h.$scope.onActionFailure (sites:481)
    at sites:410
    at angular.js:7740
    at C (angular.js:11109)
    at C (angular.js:11109)
    at C (angular.js:11109)
    at angular.js:11242
    at h.$eval (angular.js:12175)
    at h.$digest (angular.js:12004)
    at h.$apply (angular.js:12279)(anonymous function) @ angular.js:9563
http://localhost:8080/actions/admin/sites/token_login?callback=angular.callbacks._0&token=25ad59ba-bfb6-44e7-897d-95d7f5163b2a Failed to load resource: the server responded with a status of 400 (Bad Request)
angular.js:9563 TypeError: Cannot read property 'message' of undefined
    at h.$scope.onActionFailure (sites:481)
    at sites:410
    at angular.js:7740
    at C (angular.js:11109)
    at C (angular.js:11109)
    at C (angular.js:11109)
    at angular.js:11242
    at h.$eval (angular.js:12175)
    at h.$digest (angular.js:12004)
    at h.$apply (angular.js:12279)(anonymous function) @ angular.js:9563
angular.js:8227 GET http://localhost:8080/actions/admin/sites/token_login?callback=angular.callbacks._0&token=a53923b6-70fe-44dd-ae97-540f19e7a6d3 f @ angular.js:8227(anonymous function) @ angular.js:8094t @ angular.js:7967h @ angular.js:7708H @ angular.js:11100H @ angular.js:11100(anonymous function) @ angular.js:11186h.$eval @ angular.js:12175h.$digest @ angular.js:12004h.$apply @ angular.js:12279g @ angular.js:7991C @ angular.js:8196y.onreadystatechange @ angular.js:8137
angular.js:9563 TypeError: Cannot read property 'message' of undefined
    at h.$scope.onActionFailure (sites:481)
    at sites:410
    at angular.js:7740
    at C (angular.js:11109)
    at C (angular.js:11109)
    at C (angular.js:11109)
    at angular.js:11242
    at h.$eval (angular.js:12175)
    at h.$digest (angular.js:12004)
    at h.$apply (angular.js:12279)
```

**Comment by brianhyder** [comment] 2016-06-08 18:25
OK, after digging in a bit here is what I found.  The multi-site capabilities just aren't designed to work with IP addresses.  Only domains.  Fixing this would be a larger effort and should be considered for a V2 implementation.  

When a multi-site implementation starts up for the first time it creates a site off of the "siteRoot" property in the config.js file.  This is so that implementations that are already on single site mode can easily migrate and their current site becomes a child site of the whatever is the global site.

In your case (and mine) I believe that globalRoots being the same as the site root create a conflict.  They can be activated but don't have a sub-domain so the site property gets defaulted to "global" which is not allowed to have content because the global root is only there to provide a management interface.  In the cluster of a file called ```routes.js``` there is a property ```inactive_site_access``` on some of the routes.  The APIs are configured to allow this inactive site access so that plugins for global root can have access to these resources.  So while you can post data to it is just not built into the platform for the global site roots to see content data.

I have a pull request for this issue that does a lot of cleanup and fixes a couple of other issues that were uncovered during the discovery phase.  I'd like to say thank you for reporting the issue and your patience while we dug through it all.

**Closed by brianhyder** 2016-06-08 18:25 UTC
Labels: bug, in progress, question
